### ISSUE TITLE
[FEATURE REQUEST] Can you add the ability to Delete imported configuration files in bulk?

### ISSUE THREAD

**Issue by universish** [gary113/wireguard-gui-python#3]
Thank you for your efforts.

I can import the zip file with the “Import Interfaces” feature, so I can batch import the config files in the zip. 

But when there is an urgent situation where I need to delete them in bulk, I cannot delete them in bulk. For example, the country I live in is ruled by a dictator fascist jihadist bigoted Islamist regime. I am an atheist who opposes the regime.  The regime's men can raid my house and demand the data inside my computer. In such cases, I need to destroy my data quickly.

Delete feature works. But I need to delete one by one.
Can you add a batch deletion feature?

I also have to use file shredding software frequently. 
Can you add the ability to delete in bulk with file shredding?

**Comment by gary113** [comment]
I just pushed a change to master that allows selecting multiple interfaces and deleting them all at once. You can select them using Shift, Control, or simply by clicking and dragging.

Simply run the automatic installer, and it should apply the updates:

```
bash -c "$(curl -fsSL https://raw.githubusercontent.com/gary113/wireguard-gui-python/master/install.sh)"
```

If you have wgp open, it’s better to close it before updating.
