### ISSUE TITLE
Export feature is not working.

### ISSUE THREAD

**Issue by universish** [gary113/wireguard-gui-python#4]
Thank you for your efforts.

I can import the zip file with the “Import Interfaces” feature, so I can batch import the config files in the zip. 

I tried to export the config files I imported, I wanted to check if the export feature works. 

I couldn't batch export as .zip. I think there is no such feature, but I don't know.

I tried to export a single .conf config file. I couldn't export it. Steps:
1. I selected the wg-XX-<NUMBER>.conf file to export.
(If I could select several .conf files with Ctrl or select all .conf files, I could export the .conf files I want in one go. Unfortunately there is no such feature. Only one .conf file can be selected. The wireguard software for Windows has batch export and the ability to select the conf files you want and export them in batches.)
2. I clicked on the “Export” button.
3. There is no other option than Files of type: Directories. This is selected. 
(If there was a choice of file type to save, I could have chosen .zip or .conf. The wireguard software for Windows has the ability to export 1 or more config files in a single file as a .zip file. If we are going to export a single config file, it has the ability to export as .conf.)
4. I selected the export directory (folder).
5. I clicked on the Choose button.
6. I checked the directory. There is no .conf file or any other file.

**Comment by gary113** [comment]
I just uploaded a change to enable viewing logs during export. Please download the changes as follows:

```
cd /opt/wireguard-gui-python
git checkout development
git pull
```

Close all instances of wgp and reopen it, then try exporting again. After exporting, you can check the logs to see if any errors occurred.

Some considerations:

- You must select the destination folder where the zip will be exported.
- The zip file will always have the same name: wireguard_interfaces.zip.
- All interfaces will be exported, not just the one you have selected.

**Comment by universish** [comment]
```
$ cd /opt/wireguard-gui-python
git checkout development
git pull
M	run.sh
Halihazırda 'development' üzerinde
Dalınız 'origin/development' ile güncel.
hata: '.git/FETCH_HEAD' açılamıyor: Erişim engellendi
```

translated:
```
$ cd /opt/wireguard-gui-python
git checkout development
git pull
M	run.sh
Currently on 'development'
Your branch is up to date with 'origin/development'.
error: cannot open '.git/FETCH_HEAD': Access is denied
```

**Comment by universish** [comment]
Failed to update.
I tried exporting with v1.3. It exported successfully.

**Comment by gary113** [comment]
The changes I made were just to add logs; it didn’t allow you to pull due to a permissions issue. I forgot to mention that you need to run that process as the root user.

```
sudo su
Then, the other commands
```

**Comment by universish** [comment]
ok. 
no problem.
```
2024-11-14 00:00:59 ~ [##] EXPORTING TO /home/macellan/İndirilenler/wireguard_interfaces.zip START
2024-11-14 00:00:59 ~ updating: wgNL1*****.conf (deflated 15%)
2024-11-14 00:00:59 ~ updating: wgNL3*****.conf (deflated 14%)
2024-11-14 00:00:59 ~ [##] EXPORTING TO /home/macellan/İndirilenler/wireguard_interfaces.zip END
```
